/**
 * PayFlow SMT — Universal Intent Library
 *
 * Biblioteca universal de intenciones y acciones (NO respuestas fijas).
 * Seed: 100 casos del Excel Catalogo_Automatizacion_100_Casos.xlsx
 * + intenciones de carrito/pedido
 * + intenciones de gestión de catálogo/promo (admin only)
 *
 * El Agente IA genera respuestas naturales con datos del Knowledge Center.
 * Esta biblioteca define QUÉ hace cada intención, no QUÉ responde.
 */

export interface IntentDefinition {
  intent: string;
  sector: string;
  synonyms: string[];
  entities: string[];
  actionType: ActionType;
  responsePolicy: { tone: Tone; mustAskFor: string[]; fallback: string };
}

export type ActionType = "schedule" | "query_status" | "send_info" | "crm_action" | "transfer_human" | "cart_action" | "catalog_manage" | "promo_manage";
export type Tone = "profesional" | "cordial" | "urgente";

export const INTENT_LIBRARY: IntentDefinition[] = [
  { intent: "#AGENDAR_CITA_MEDICA", sector: "Clínica / Doctores", synonyms: ["buenas", "necesito", "agendar", "consulta", "médica", "traumatólogo"], entities: ["especialidad", "rango"], actionType: "schedule", responsePolicy: { tone: "profesional", mustAskFor: ["especialidad"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CITA_LIMPIEZA_DENTAL", sector: "Odontología", synonyms: ["hola", "quiero", "reservar", "turno", "profilaxis", "limpieza"], entities: ["servicio"], actionType: "schedule", responsePolicy: { tone: "profesional", mustAskFor: ["servicio"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#URGENCIA_DENTAL", sector: "Odontología", synonyms: ["ayuda", "duele", "muchísimo", "muela", "tengo", "cara"], entities: ["urgencia", "síntoma"], actionType: "schedule", responsePolicy: { tone: "profesional", mustAskFor: ["urgencia"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#COTIZACION_ORTODONCIA", sector: "Odontología", synonyms: ["cuánto", "cuestan", "brackets", "estéticos", "ortodoncia", "invisible"], entities: ["interes"], actionType: "send_info", responsePolicy: { tone: "profesional", mustAskFor: ["interes"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#POSTOP_EXTRACCION", sector: "Odontología", synonyms: ["sacaron", "muela", "juicio", "ayer", "estoy", "sangrando"], entities: ["procedimiento", "sintoma"], actionType: "send_info", responsePolicy: { tone: "profesional", mustAskFor: ["procedimiento"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CONFIRMAR_CITA", sector: "Clínica / Doctores", synonyms: ["hola", "llegó", "mensaje", "confirmar", "cita", "mañana"], entities: ["accion", "especialidad"], actionType: "schedule", responsePolicy: { tone: "profesional", mustAskFor: ["accion"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CANCELAR_CITA_MEDICA", sector: "Clínica / Doctores", synonyms: ["hola", "podré", "cita", "médica", "imprevisto"], entities: ["accion", "id_cita"], actionType: "schedule", responsePolicy: { tone: "profesional", mustAskFor: ["accion"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#REQUISITO_EXAMEN_SANGRE", sector: "Clínica / Doctores", synonyms: ["tengo", "exámenes", "glucosa", "perfil", "lipídico", "mañana"], entities: ["examen", "requisito"], actionType: "send_info", responsePolicy: { tone: "profesional", mustAskFor: ["examen"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#RESTRICCION_ECOGRAFIA", sector: "Clínica / Doctores", synonyms: ["debo", "tomar", "agua", "antes", "hacerme", "ecografía"], entities: ["estudio"], actionType: "send_info", responsePolicy: { tone: "profesional", mustAskFor: ["estudio"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#VALOR_CONSULTA", sector: "Clínica / Doctores", synonyms: ["precio", "tiene", "consulta", "médica", "general", "especialidad"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "profesional", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CONVENIO_ASEGURADORAS", sector: "Clínica / Doctores", synonyms: ["trabajan", "seguro", "médico", "mapfre", "saludsa"], entities: ["aseguradora"], actionType: "send_info", responsePolicy: { tone: "profesional", mustAskFor: ["aseguradora"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#RESULTADO_LABORATORIO", sector: "Clínica / Doctores", synonyms: ["cómo", "puedo", "descargar", "resultados", "análisis", "sangre"], entities: ["solicitud"], actionType: "query_status", responsePolicy: { tone: "profesional", mustAskFor: ["solicitud"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#BLANQUEAMIENTO_DENTAL", sector: "Odontología", synonyms: ["blanqueamiento", "dental", "duele", "produce", "sensibilidad"], entities: ["tratamiento"], actionType: "send_info", responsePolicy: { tone: "profesional", mustAskFor: ["tratamiento"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#DISENO_SONRISA", sector: "Odontología", synonyms: ["cuánto", "dura", "tratamiento", "diseño", "sonrisa", "carillas"], entities: ["tratamiento"], actionType: "schedule", responsePolicy: { tone: "profesional", mustAskFor: ["tratamiento"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#RESULTADO_IMAGENES", sector: "Clínica / Doctores", synonyms: ["están", "listos", "resultados", "resonancia", "magnética"], entities: ["estudio"], actionType: "query_status", responsePolicy: { tone: "profesional", mustAskFor: ["estudio"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#UBICACION_SUCURSALES", sector: "Clínica / Doctores", synonyms: ["dirección", "queda", "clínica", "piso", "atienden", "oftalmología"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "profesional", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#METODOS_PAGO_CLINICA", sector: "Clínica / Doctores", synonyms: ["puedo", "pagar", "consultas", "tarjeta", "crédito", "diferido"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "profesional", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#REPARACION_PROTESIS", sector: "Odontología", synonyms: ["rompió", "prótesis", "dental", "pueden", "reparar", "mismo"], entities: ["servicio"], actionType: "schedule", responsePolicy: { tone: "profesional", mustAskFor: ["servicio"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CERTIFICADO_MEDICO", sector: "Clínica / Doctores", synonyms: ["necesito", "certificado", "médico", "reposo", "trabajo"], entities: ["solicitud"], actionType: "send_info", responsePolicy: { tone: "profesional", mustAskFor: ["solicitud"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#VACUNACIÓN_INFANTIL", sector: "Clínica / Doctores", synonyms: ["tienen", "disponible", "vacuna", "papiloma", "humano", "influenza"], entities: ["vacuna"], actionType: "query_status", responsePolicy: { tone: "profesional", mustAskFor: ["vacuna"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#TELEMEDICINA", sector: "Clínica / Doctores", synonyms: ["ofrecen", "consultas", "médicas", "virtuales", "videollamada"], entities: ["modalidad"], actionType: "cart_action", responsePolicy: { tone: "profesional", mustAskFor: ["modalidad"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#GUARDAS_BRUXISMO", sector: "Odontología", synonyms: ["aprieto", "mucho", "dientes", "noche", "despierto", "dolor"], entities: ["sintoma"], actionType: "schedule", responsePolicy: { tone: "profesional", mustAskFor: ["sintoma"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CIRUGIA_AMBULATORIA", sector: "Clínica / Doctores", synonyms: ["cuáles", "pasos", "programar", "cirugía", "ambulatoria"], entities: ["solicitud"], actionType: "crm_action", responsePolicy: { tone: "profesional", mustAskFor: ["solicitud"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#VISITAS_HOSPITALIZACION", sector: "Clínica / Doctores", synonyms: ["cuál", "horario", "visitas", "pacientes", "ingresados", "habitación"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "profesional", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#ATENCION_URGENCIAS_24H", sector: "Clínica / Doctores", synonyms: ["área", "emergencias", "atiende", "horas"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "profesional", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#RESERVA_MESA", sector: "Restaurante", synonyms: ["hola", "gustaría", "reservar", "mesa", "personas", "este"], entities: ["fecha", "hora", "20", "personas"], actionType: "schedule", responsePolicy: { tone: "cordial", mustAskFor: ["fecha"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CARTA_MENU_PDF", sector: "Restaurante", synonyms: ["tienen", "menú", "digital", "fotos", "precios"], entities: ["solicitud"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["solicitud"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PEDIDO_DELIVERY_RAPIDO", sector: "Restaurante", synonyms: ["quiero", "pedir", "hamburguesa", "doble", "queso", "papas"], entities: ["producto", "envio"], actionType: "crm_action", responsePolicy: { tone: "cordial", mustAskFor: ["producto"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PEDIDO_PARA_LLEVAR", sector: "Restaurante", synonyms: ["quiero", "hacer", "pedido", "retirar", "local", "minutos"], entities: ["modalidad"], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: ["modalidad"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#ALERGENOS_INTOLERANCIAS", sector: "Restaurante", synonyms: ["celíaco", "tienen", "platos", "preparados", "cocina", "separada"], entities: ["condicion"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["condicion"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PROMO_HAPPY_HOUR", sector: "Restaurante", synonyms: ["tienen", "promoción", "happy", "hour", "cocteles"], entities: ["interes"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["interes"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PLATOS_NIÑOS", sector: "Restaurante", synonyms: ["tienen", "menú", "infantil", "zona", "juegos", "niños"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CORCHO_LIBRE", sector: "Restaurante", synonyms: ["puedo", "llevar", "propio", "vino", "restaurante", "cuánto"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PET_FRIENDLY_REST", sector: "Restaurante", synonyms: ["puede", "ingresar", "mascota", "mesas", "terraza"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PEDIDO_CUMPLEAÑOS", sector: "Restaurante", synonyms: ["celebrar", "cumpleaños", "ustedes", "regalan", "algún", "postre"], entities: ["motivo"], actionType: "crm_action", responsePolicy: { tone: "cordial", mustAskFor: ["motivo"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CATERING_EMPRESARIAL", sector: "Restaurante", synonyms: ["necesito", "servicio", "catering", "bocaditos", "reunión", "personas"], entities: ["servicio", "personas"], actionType: "crm_action", responsePolicy: { tone: "cordial", mustAskFor: ["servicio"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#METODOS_PAGO_REST", sector: "Restaurante", synonyms: ["aceptan", "tarjetas", "débito", "crédito", "transferencia", "bancaria"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#ESTADO_PEDIDO_DELIVERY", sector: "Restaurante", synonyms: ["hice", "pedido", "hace", "minutos", "llega", "dónde"], entities: ["solicitud"], actionType: "query_status", responsePolicy: { tone: "cordial", mustAskFor: ["solicitud"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#FACTURA_CONSUMO", sector: "Restaurante", synonyms: ["necesito", "solicitar", "factura", "electrónica", "consumo", "anoche"], entities: ["solicitud"], actionType: "crm_action", responsePolicy: { tone: "cordial", mustAskFor: ["solicitud"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#RESERVA_DEPOSITOS", sector: "Restaurante", synonyms: ["piden", "algún", "abono", "reservar", "mesas", "personas"], entities: ["personas", "accion"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["personas"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#HORARIO_COCINA", sector: "Restaurante", synonyms: ["hora", "cierra", "cocina", "restaurante"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#BUFFET_ALMUERZO", sector: "Restaurante", synonyms: ["tienen", "opción", "almuerzo", "ejecutivo", "buffet", "lunes"], entities: ["oferta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["oferta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#RESERVA_CANDLELIGHT", sector: "Restaurante", synonyms: ["quiero", "mesa", "decorada", "velas", "flores", "aniversario"], entities: ["motivo"], actionType: "schedule", responsePolicy: { tone: "cordial", mustAskFor: ["motivo"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PLATOS_ESTRELLA", sector: "Restaurante", synonyms: ["cuál", "plato", "estrella", "vendido", "restaurante"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#MODIFICAR_RESERVA", sector: "Restaurante", synonyms: ["necesito", "cambiar", "reserva", "personas", "lugar"], entities: ["accion"], actionType: "schedule", responsePolicy: { tone: "cordial", mustAskFor: ["accion"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#RESERVA_PELUQUERIA", sector: "Spa / Peluquería", synonyms: ["quiero", "turno", "balayage", "tinte", "este", "viernes"], entities: ["servicio", "fecha"], actionType: "schedule", responsePolicy: { tone: "cordial", mustAskFor: ["servicio"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CITA_MASAJE_PAREJA", sector: "Spa / Peluquería", synonyms: ["quiero", "consultar", "paquete", "masaje", "pareja", "semana"], entities: ["servicio"], actionType: "schedule", responsePolicy: { tone: "cordial", mustAskFor: ["servicio"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#MANICURE_PEDICURE", sector: "Spa / Peluquería", synonyms: ["tienen", "espacio", "tarde", "manicure", "pedicure", "ruso"], entities: ["servicio"], actionType: "schedule", responsePolicy: { tone: "cordial", mustAskFor: ["servicio"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PRECIOS_DEPILACION_LASER", sector: "Spa / Peluquería", synonyms: ["cuánto", "cuesta", "sesión", "depilación", "láser", "diodo"], entities: ["tratamiento"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["tratamiento"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#TRATAMIENTO_CAPILAR", sector: "Spa / Peluquería", synonyms: ["tengo", "cabello", "seco", "maltratado", "tratamiento", "recomiendan"], entities: ["sintoma"], actionType: "schedule", responsePolicy: { tone: "cordial", mustAskFor: ["sintoma"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#DISPONIBILIDAD_HOY", sector: "Spa / Peluquería", synonyms: ["tienen", "algún", "hueco", "libre", "mismo", "después"], entities: ["disponibilidad"], actionType: "schedule", responsePolicy: { tone: "cordial", mustAskFor: ["disponibilidad"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CUIDADO_POST_KERATINA", sector: "Spa / Peluquería", synonyms: ["hice", "keratina", "ayer", "cuántos", "días", "puedo"], entities: ["post_servicio"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["post_servicio"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PAQUETE_NOVIA", sector: "Spa / Peluquería", synonyms: ["necesito", "cotizar", "paquete", "completo", "peinado", "maquillaje"], entities: ["servicio"], actionType: "transfer_human", responsePolicy: { tone: "cordial", mustAskFor: ["servicio"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#FACIAL_ANTIACNE", sector: "Spa / Peluquería", synonyms: ["limpieza", "facial", "incluye", "extracción", "puntos", "negros"], entities: ["tratamiento"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["tratamiento"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PRODUCTOS_VENTA", sector: "Spa / Peluquería", synonyms: ["venden", "productos", "cuidado", "casa", "como", "olaplex"], entities: ["producto"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["producto"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CANCELLATION_POLICY_SPA", sector: "Spa / Peluquería", synonyms: ["cuánta", "anticipación", "debo", "cancelar", "cita", "penalización"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#EXTENSIONES_PESTAÑAS", sector: "Spa / Peluquería", synonyms: ["cuánto", "duran", "extensiones", "pestañas", "pelo", "pelo"], entities: ["servicio"], actionType: "schedule", responsePolicy: { tone: "cordial", mustAskFor: ["servicio"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#MADEROTERAPIA_REDUCTORA", sector: "Spa / Peluquería", synonyms: ["maderoterapia", "masajes", "reductores", "ayudan", "reducir", "medidas"], entities: ["tratamiento"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["tratamiento"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#LIFTING_PESTAÑAS", sector: "Spa / Peluquería", synonyms: ["cuál", "diferencia", "entre", "lifting", "pestañas", "extensiones"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PAGO_ABONO_CITA", sector: "Spa / Peluquería", synonyms: ["intenté", "agendar", "pero", "pide", "abono", "seguro"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#SUCURSAL_MAS_CERCANA", sector: "Spa / Peluquería", synonyms: ["tienen", "sucursal", "sector", "norte", "ciudad"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#MEMBRESIA_SPA", sector: "Spa / Peluquería", synonyms: ["tienen", "pases", "mensuales", "membresías", "peluquería"], entities: ["oferta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["oferta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#ATENCION_HOMBRES", sector: "Spa / Peluquería", synonyms: ["peluquería", "también", "atienden", "barba", "cortes", "caballeros"], entities: ["servicio"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["servicio"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#GIFT_CARD_IMPRESA", sector: "Spa / Peluquería", synonyms: ["quiero", "comprar", "gift", "card", "física", "cajita"], entities: ["producto"], actionType: "crm_action", responsePolicy: { tone: "cordial", mustAskFor: ["producto"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#MICROBLADING_CEJAS", sector: "Spa / Peluquería", synonyms: ["microblading", "cejas", "duele", "cuánto", "tiempo", "dura"], entities: ["tratamiento"], actionType: "schedule", responsePolicy: { tone: "cordial", mustAskFor: ["tratamiento"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#ESTADO_ENVIOS", sector: "Comercio / Tienda", synonyms: ["quiero", "saber", "estado", "compra", "10492"], entities: ["orden_id"], actionType: "query_status", responsePolicy: { tone: "cordial", mustAskFor: ["orden_id"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#DISPONIBILIDAD_TALLAS", sector: "Comercio / Tienda", synonyms: ["tienen", "chaqueta", "jeans", "talla"], entities: ["producto", "talla"], actionType: "query_status", responsePolicy: { tone: "cordial", mustAskFor: ["producto"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CAMBIO_DE_PRENDA", sector: "Comercio / Tienda", synonyms: ["camiseta", "compré", "internet", "quedó", "grande", "cómo"], entities: ["tramite"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["tramite"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#ENVIO_GRATIS", sector: "Comercio / Tienda", synonyms: ["partir", "monto", "compra", "envío", "gratis"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CATALOGO_WHATSAPP", sector: "Comercio / Tienda", synonyms: ["tienen", "catálogo", "tienda", "instagram"], entities: ["solicitud"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["solicitud"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#TIENDA_FISICA_HORARIO", sector: "Comercio / Tienda", synonyms: ["hora", "abren", "cierran", "local", "centro", "comercial"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#FACTURACION_DATOS", sector: "Comercio / Tienda", synonyms: ["necesito", "factura", "empresa", "pedido"], entities: ["solicitud"], actionType: "crm_action", responsePolicy: { tone: "cordial", mustAskFor: ["solicitud"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#GARANTIA_PRODUCTO", sector: "Comercio / Tienda", synonyms: ["compré", "electrodoméstico", "hace", "semanas", "dejó", "encender"], entities: ["caso"], actionType: "crm_action", responsePolicy: { tone: "cordial", mustAskFor: ["caso"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CANCELAR_ORDEN", sector: "Comercio / Tienda", synonyms: ["quiero", "cancelar", "compra", "hice", "hace", "hora"], entities: ["accion"], actionType: "query_status", responsePolicy: { tone: "cordial", mustAskFor: ["accion"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#RESERVAR_TIENDA", sector: "Comercio / Tienda", synonyms: ["puedo", "apartar", "prenda", "pasar", "pagarla", "mañana"], entities: ["accion"], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: ["accion"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#MEDIOS_DE_PAGO_ECOM", sector: "Comercio / Tienda", synonyms: ["tienen", "opción", "pagar", "contra", "entrega", "recibir"], entities: ["modalidad"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["modalidad"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#DESCUENTO_PRIMERA_COMPRA", sector: "Comercio / Tienda", synonyms: ["tienen", "algún", "cupón", "bienvenida", "nuevos", "clientes"], entities: ["cupon"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["cupon"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#MAYORISTAS_VENTAS", sector: "Comercio / Tienda", synonyms: ["quiero", "comprar", "mayor", "revender", "negocio"], entities: ["interes"], actionType: "transfer_human", responsePolicy: { tone: "cordial", mustAskFor: ["interes"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#GUIA_DE_TALLAS", sector: "Comercio / Tienda", synonyms: ["talla", "pedir", "dónde", "encuentro", "guía", "medidas"], entities: ["solicitud"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["solicitud"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PRODUTO_AGOTADO", sector: "Comercio / Tienda", synonyms: ["cuándo", "vuelve", "estar", "disponible", "vestido", "rojo"], entities: ["producto", "estado"], actionType: "crm_action", responsePolicy: { tone: "cordial", mustAskFor: ["producto"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PAGO_FALLIDO", sector: "Comercio / Tienda", synonyms: ["intenté", "pagar", "tarjeta", "pero", "sale", "error"], entities: ["problema"], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: ["problema"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#EMPAQUE_REGALO", sector: "Comercio / Tienda", synonyms: ["tienen", "servicio", "empaque", "regalo", "tarjeta", "personalizada"], entities: ["opcion"], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: ["opcion"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#RECLAMO_PRODUCTO_INCOMPLETO", sector: "Comercio / Tienda", synonyms: ["recibí", "paquete", "pero", "falta", "accesorio", "venía"], entities: ["reclamo"], actionType: "crm_action", responsePolicy: { tone: "cordial", mustAskFor: ["reclamo"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#TIEMPO_ENTREGA_LOCAL", sector: "Comercio / Tienda", synonyms: ["compro", "cuándo", "llega", "pedido", "dentro", "ciudad"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CLUB_PUNTOS", sector: "Comercio / Tienda", synonyms: ["cómo", "funciona", "programa", "puntos", "compras"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PASE_DE_PRUEBA_GYM", sector: "Gym / Fitness", synonyms: ["quiero", "probar", "gimnasio", "gratis"], entities: ["solicitud"], actionType: "schedule", responsePolicy: { tone: "cordial", mustAskFor: ["solicitud"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#COSTO_MEMBRESIA_GYM", sector: "Gym / Fitness", synonyms: ["cuánto", "cuesta", "mensualidad", "plan", "anual", "gimnasio"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#HORARIO_CLASES_GRUPALES", sector: "Gym / Fitness", synonyms: ["hora", "clases", "spinning", "zumba", "pilates"], entities: ["solicitud"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["solicitud"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#RESERVA_HABITACION", sector: "Hospedaje / Hotel", synonyms: ["quiero", "cotizar", "habitación", "doble", "este", "semana"], entities: ["habitacion", "noches"], actionType: "schedule", responsePolicy: { tone: "cordial", mustAskFor: ["habitacion"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#CHECKIN_LATE", sector: "Hospedaje / Hotel", synonyms: ["llegaremos", "hotel", "medianoche", "recepción", "horas"], entities: ["consulta"], actionType: "crm_action", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PISCINA_USO_DIA", sector: "Hospedaje / Hotel", synonyms: ["venden", "pases", "pass", "usar", "piscina", "hospedarme"], entities: ["servicio"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["servicio"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#HABLAR_CON_HUMANO", sector: "Servicios / Varios", synonyms: ["necesito", "hablar", "urgentemente", "persona", "quiero", "respuestas"], entities: ["accion"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["accion"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#RECLAMO_SERVICIO", sector: "Servicios / Varios", synonyms: ["quiero", "ingresar", "reclamo", "formal", "cobro", "duplicado"], entities: ["reclamo"], actionType: "crm_action", responsePolicy: { tone: "cordial", mustAskFor: ["reclamo"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#UBICACIONES_OFICINAS", sector: "Servicios / Varios", synonyms: ["tienen", "oficinas", "físicas", "donde", "pueda", "hacer"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#METODOS_CONTACTO", sector: "Servicios / Varios", synonyms: ["número", "teléfono", "correo", "puedo", "comunicarme", "directamente"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#TRABAJO_VACANTES", sector: "Servicios / Varios", synonyms: ["tienen", "vacantes", "empleo", "abiertas", "enviar", "hoja"], entities: ["solicitud"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["solicitud"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#COTIZACION_PERSONALIZADA", sector: "Servicios / Varios", synonyms: ["necesito", "presupuesto", "medida", "proyecto", "corporativo", "grande"], entities: ["solicitud"], actionType: "crm_action", responsePolicy: { tone: "cordial", mustAskFor: ["solicitud"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#HORARIOS_FERIADOS_GRAL", sector: "Servicios / Varios", synonyms: ["atenderán", "normalidad", "este", "próximo", "feriado", "nacional"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#DATOS_BANCARIOS", sector: "Servicios / Varios", synonyms: ["necesito", "datos", "cuenta", "bancaria", "hacer", "transferencia"], entities: ["solicitud"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["solicitud"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
  { intent: "#PROTECCION_DATOS", sector: "Servicios / Varios", synonyms: ["cómo", "protegen", "datos", "personales", "suministrados", "este"], entities: ["consulta"], actionType: "send_info", responsePolicy: { tone: "cordial", mustAskFor: ["consulta"], fallback: "Disculpa, no tengo esa información en este momento. Te derivaré con un asesor humano." } },
];

// ─── Carrito & Pedido intents (universales, cualquier sector) ────────
export const CART_INTENTS: IntentDefinition[] = [
  { intent: "#CARRITO_AGREGAR", sector: "Universal", synonyms: ["quiero","agrega","añade","dame","llévame","ponme","para llevar","uno","dos","tres"], entities: ["productos","cantidades"], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: ["productos"], fallback: "¿Qué producto te gustaría agregar?" } },
  { intent: "#CARRITO_AGREGAR_MULTIPLE", sector: "Universal", synonyms: ["dos","tres","y","con","más","también","además"], entities: ["productos","cantidades"], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: ["productos"], fallback: "Dime los productos y cantidades que quieres." } },
  { intent: "#CARRITO_QUITAR", sector: "Universal", synonyms: ["quita","elimina","saca","remueve","borra","no quiero"], entities: ["producto_o_indice"], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: ["producto_o_indice"], fallback: "¿Qué producto quieres quitar del carrito?" } },
  { intent: "#CARRITO_REEMPLAZAR", sector: "Universal", synonyms: ["cambia","reemplaza","cambio","en vez de","sustituye"], entities: ["producto_viejo","producto_nuevo"], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: ["producto_viejo","producto_nuevo"], fallback: "¿Qué producto quieres reemplazar y por cuál?" } },
  { intent: "#CARRITO_MODIFICAR_CANTIDAD", sector: "Universal", synonyms: ["cantidad","cambia la cantidad","ponle","sube a","baja a","dame más","dame menos"], entities: ["producto_o_indice","cantidad"], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: ["producto_o_indice","cantidad"], fallback: "¿De qué producto y a qué cantidad quieres cambiar?" } },
  { intent: "#CARRITO_SELECCIONAR_NUMERO", sector: "Universal", synonyms: ["el","la","número","numero","opción","opcion","código","codigo","letra"], entities: ["selector"], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: ["selector"], fallback: "¿Qué número/código/letra eliges?" } },
  { intent: "#CARRITO_CONSULTAR", sector: "Universal", synonyms: ["carrito","qué llevo","que llevo","mi pedido","mi orden","qué pedí","que pedí"], entities: [], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: [], fallback: "Tu carrito está vacío." } },
  { intent: "#CARRITO_CONSULTAR_TOTAL", sector: "Universal", synonyms: ["total","cuánto llevo","cuanto llevo","cuánto es","cuanto es","a cuánto","a cuanto","subtotal","cuánto debo","cuanto debo"], entities: [], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: [], fallback: "Tu carrito está vacío." } },
  { intent: "#CARRITO_VER_MENU", sector: "Universal", synonyms: ["menú","menu","carta","ver opciones","ver productos","mostrar menú","mostrar menu","ver catálogo","ver catalogo","qué tienen","que tienen","quieren ver","muéstrame","muestrame"], entities: [], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: [], fallback: "No tengo productos cargados en el catálogo." } },
  { intent: "#CARRITO_NUEVO_PEDIDO", sector: "Universal", synonyms: ["nuevo pedido","empezar de nuevo","limpiar carrito","vaciar carrito","borrar todo","nueva orden"], entities: [], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: [], fallback: "Listo, carrito vaciado. ¿Qué te gustaría pedir?" } },
  { intent: "#CARRITO_CONFIRMAR_PEDIDO", sector: "Universal", synonyms: ["confirmar","confirmo","ya está","ya esta","listo","proceder","checkout","finalizar","sí eso","si eso"], entities: [], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: [], fallback: "Tu carrito está vacío. Agrega productos primero." } },
  { intent: "#CARRITO_CANCELAR_PEDIDO", sector: "Universal", synonyms: ["cancelar","cancelo","no quiero nada","olvida","dejar","abortar"], entities: [], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: [], fallback: "No hay pedido activo para cancelar." } },
  { intent: "#CARRITO_ACLARAR_AMBIGUO", sector: "Universal", synonyms: ["cuál","cual","a qué te refieres","no entiendo","cuáles","cuales"], entities: ["producto_ambiguo"], actionType: "cart_action", responsePolicy: { tone: "cordial", mustAskFor: ["producto_ambiguo"], fallback: "¿Podrías ser más específico?" } },
];

// ─── Catálogo management intents (ADMIN only) ────────────────────────
export const CATALOG_MANAGE_INTENTS: IntentDefinition[] = [
  { intent: "#CATALOGO_AGREGAR", sector: "Admin", synonyms: ["agrega producto","nuevo producto","crea producto","añade producto","dar de alta"], entities: ["nombre","precio","categoria"], actionType: "catalog_manage", responsePolicy: { tone: "profesional", mustAskFor: ["nombre","precio"], fallback: "Necesito nombre y precio del producto." } },
  { intent: "#CATALOGO_ELIMINAR", sector: "Admin", synonyms: ["elimina producto","quita producto","desactiva producto","borra producto"], entities: ["nombre_o_id"], actionType: "catalog_manage", responsePolicy: { tone: "profesional", mustAskFor: ["nombre_o_id"], fallback: "¿Qué producto quieres eliminar?" } },
  { intent: "#CATALOGO_MODIFICAR_PRECIO", sector: "Admin", synonyms: ["cambia precio","modifica precio","nuevo precio","actualiza precio"], entities: ["nombre_o_id","precio"], actionType: "catalog_manage", responsePolicy: { tone: "profesional", mustAskFor: ["nombre_o_id","precio"], fallback: "¿De qué producto y a qué precio?" } },
  { intent: "#CATALOGO_MODIFICAR_DESC", sector: "Admin", synonyms: ["cambia descripción","modifica descripción","nueva descripción"], entities: ["nombre_o_id","descripcion"], actionType: "catalog_manage", responsePolicy: { tone: "profesional", mustAskFor: ["nombre_o_id","descripcion"], fallback: "¿De qué producto y qué descripción nueva?" } },
  { intent: "#PROMO_CREAR", sector: "Admin", synonyms: ["crea promoción","nueva promo","crear descuento","lanzar oferta"], entities: ["nombre","tipo","valor","categoria"], actionType: "promo_manage", responsePolicy: { tone: "profesional", mustAskFor: ["nombre","tipo","valor"], fallback: "Necesito nombre, tipo y valor de la promoción." } },
  { intent: "#PROMO_LISTAR", sector: "Admin", synonyms: ["ver promociones","lista promos","promociones activas","ofertas activas"], entities: [], actionType: "promo_manage", responsePolicy: { tone: "profesional", mustAskFor: [], fallback: "No hay promociones activas." } },
];

export const ALL_INTENTS: IntentDefinition[] = [...INTENT_LIBRARY, ...CART_INTENTS, ...CATALOG_MANAGE_INTENTS];

export function getIntentDefinition(intent: string): IntentDefinition | undefined {
  return ALL_INTENTS.find((i) => i.intent === intent);
}

export function isCatalogManageIntent(intent: string): boolean {
  return CATALOG_MANAGE_INTENTS.some((i) => i.intent === intent);
}

export function isCartIntent(intent: string): boolean {
  return CART_INTENTS.some((i) => i.intent === intent);
}
